### ISSUE TITLE
Explain how to integrate new components such as Ionic

### ISSUE THREAD

**Issue by ludovicc** [jokade/scalajs-angulate#18]
Hello,

I would like to use scalajs-angulate on a Ionic project. How can I add the bindings to Ionic services such as $ionicPlatform? Using Traits and registering the services with module.serviceOf[]() ? The project olivergg/scalajs-ionic-starttabs does some very basic bindings to Ionic, I would like to do the same with angulate.

**Comment by jokade** [comment]
Hi,

if your `$ionicPlatform` is an angular service already provided by an angular module, you only would need to inject it into the constructor:

``` scala
class FooCtrl($ionicPlatform: js.Dynamic) extends Controller {
  /* ... */
}

// - or, if you want it type safe -
trait IonicPlatform extends js.Object {
  def ready(cb: js.Function) : Unit = js.native
}

class FooCtrl($ionicPlatform: IonicPlatform)  extends Controller {
  /* ... */
}
```

`module.serviceOf` is only used when you want to register a class extending `Service`.
If the implementation for `$ionicPlatform` is provided by an external JS library you could write a binding trait and register the 3rd party module using the plain angular `module.service()` method:

``` scala
module.service("$ionicPlatform", js.Array( 
  () => js.Dynamic.global.ionic /* or whatever */
))
```

BTW: I'm currently preparing the 0.1 release; I hope to get it out by the weekend (and published to sonatype)
