### ISSUE TITLE
Generalize the support for function DI

### ISSUE THREAD

**Issue by ludovicc** [jokade/scalajs-angulate#25]
Function DI, as supported by the macro on Module.run and Module.config, can be generalized.
The idea is have a lightweight wrapper containing the inline array annotation of function DI.
This lightweight wrapper is generated from an implicit convertion and the macro createFunctionDIArray()

**Comment by jokade** [comment]
@ludovicc If it's alright for you, I assign you to this issue and add it to the 0.2 milestone

**Comment by ludovicc** [comment]
ok
