### ISSUE TITLE
Isomorphic rich web apps - Server-side pre-render support

### ISSUE THREAD

**Issue by dario-liberman-jav** [jokade/scalajs-angulate#34]
What would it take to support server-side pre-rendering on the JVM for a pure Scala AngularJs App?

Think of SEO (bots) or first-page render-time (attach full angular-js in the background while browser renders the page).

Some people are doing it in Node.js, but not for Angular:
• http://emberjs.com/blog/2014/12/22/inside-fastboot-the-road-to-server-side-rendering.html
• https://www.npmjs.com/package/backbone-serverside
• https://gist.github.com/StephanHoyer/bddccd9e159828867d2a
• https://prerender.io/ 
• http://blog.risingstack.com/from-angularjs-to-react-the-isomorphic-way/

**Comment by jokade** [comment]
Well, unless you want to re-implement AngularJS (and probably a major part of the DOM+JS API along with it) for the JVM, I don't see a way to support server-side pre-rendering in pure Scala on the JVM. However, there is a new JS runtime for the JVM called [DynJS](http://dynjs.org/), along with a JVM 'implementation' of Node.js: [Nodyn](http://nodyn.io/).

**Comment by dario-liberman-jav** [comment]
Re-implementing AngularJS on the JVM to support pre-rendering should not be that difficult; it is about invoking REST APIs and evaluating the template.
Regarding virtual DOM APIs, there are plenty of libraries available for the JVM.
If all the code is in Scala, running server-side to generate the initial HTML should be possible.
I am just not sure how big of an effort it would all be.

But the path you indicate, DynJS (or Nashorn perhaps?), could be an easier path indeed.
