### ISSUE TITLE
Prepare 0.2 release

### ISSUE THREAD

**Issue by jokade** [jokade/scalajs-angulate#40]
@ludovicc Hi, I'd like to publish the 0.2 release soon. Which of your branches/ open issues should be included in the release? If any, could you give me an estimate when these improvements will be ready?
I'm currently working on Angular.dart / Angular2 style Components, which I hope to include in the release.
-- Johannes

**Comment by ludovicc** [comment]
Hello,

I have mostly finished the work on Directives, but testing is probably
more challenging, it can wait.

I have a branch where I use a simple @JSExportAll annotation for
controllers, it works well and seem so much easier than using a macro to
export the contents of the controller in the scope. Can you have a look
and tell me if you like it? Look at ControlerTest or my bigger sample
project using Ionic and this style of controllers,
https://github.com/ludovicc/scalajs-ionic-tabs.

About Components, have you seen this discussion?:
https://github.com/angular/angular.js/issues/10007

Ludovic

**Comment by jokade** [comment]
Thanks for the link to the angular.js discussion; I didn't know about this.
My motiviation for components is to make migration from angular 1.x to Angular2 (hopefully) less painful with angulate, i.e. write Angular2-style components for Angular1, which later can be translated into Angular2 syntax by angulate.

Thanks for your work on the directive API; I've scheduled the 0.2 release for next Friday (I hope we can close #43 until then). I've created a page with [release notes](https://github.com/jokade/scalajs-angulate/wiki/Version-History); could please add some information about your major changes? Thanks,

Johannes
