### ISSUE TITLE
Can't use controller in $routeProvider with controller's default name

### ISSUE THREAD

**Issue by joaopmafra** [jokade/scalajs-angulate#47]
Hi there!,

First, thank you very much for all the work until now. The library is small, clean... you rock!

It seems it's not possible to use the controller's default name when registering routes. If I

``` scala
    val module = angular.createModule("ngApp", Seq("ngRoute"))

    module.controllerOf[OneCtrl]
    module.controllerOf[TwoCtrl]("TwoCtrl")

    module.config( ($routeProvider: RouteProvider) => {
      $routeProvider
        // doesn't work
        .when("/one", Route(controller = "OneCtrl", templateUrl = "/one.html"))
        // doesn't work too
        .when("/one", Route(controller = "oneCtrl", templateUrl = "/one.html"))
        // only this works
        .when("/two", Route(controller = "TwoCtrl", templateUrl = "/two.html"))
    })
```

only the last route will work.

Is this correct? Am I forgetting something?

I'm using angulate version 0.2-SNAPSHOT and scalajs 0.6.2.

Thanks in advance.

**Comment by jokade** [comment]
Is `OneCtrl` defined in a package? If so, please try using the fully qualified name in your Route definition, i.e. `Route(controller = "foo.bar.OneCtrl")`.

**Comment by joaopmafra** [comment]
Yes, with the fully qualified name it works. Thank you.
