### ISSUE TITLE
you must use locationProvider.html5Mode?

### ISSUE THREAD

**Issue by Miuler** [jokade/scalajs-angulate#49]
Hi, with angularjs i must add $locationProvider.html5Mode(true), for angulate you also need?

**Comment by jokade** [comment]
I'm not sure, if I understand your question correctly; angulate is mostly a binding library that also supports some compile-time macros to simplify the development of Angular.js applications with Scala. It does not change how Angular.js works at run time. Hence, if you need to set `$locationProvider.html5Mode(true)` should not depend on whether you use angulate, or not. 

I will add the interface for "$locationProvider" shortly.

**Comment by Miuler** [comment]
Thanks @jokade, now all ok :+1:
