### ISSUE TITLE
Custom validation via ng-messages

### ISSUE THREAD

**Issue by ghost** [jokade/scalajs-angulate#61]
Hello there,

I have been porting a legacy angular app over to angulate (extremely successfully thus far!). However, I've hit a roadblock when attempting to implement some custom validation for a couple of forms.

I have got the following directive which is placed on inputs in order to ensure that the current model value is valid:

``` scala
class TypecheckDirective extends Directive {
    override type ControllerType    = js.Dynamic
    override type ScopeType             = js.Dynamic
    override val controllerAs           = "typecheck"

    override def require = "ngModel"

    override def postLink(scope: ScopeType, element: JQLite, attrs: Attributes, ngModel: js.Dynamic) =  {
        ngModel.$validators.customvalidation = { (modelValue: js.Any) =>
            g.console.log("Model value is:" + modelValue)
            // $c_sjsr_UndefinedBehaviorError {s$1: "An undefined behavior was detected: undefined is not an instance of java.lang.String", e$1: $c_jl_ClassCastException, stackTrace$1: null, stackdata: TypeError: this.undef is not a function, constructor: function…}
            false
        }
    }
}
```

``` jade
form( name = "loginForm")
  input( typecheck, ng-model = "ctrl.email", required)
  div( ng-if = "loginForm.$error")
    label( ng-message = "custom_validation") This is an error!
```

The console.log is shown just fine (showing the current model value), but whenever false is returned (representing an invalid input), angular keeps throwing the following exception:

$c_sjsr_UndefinedBehaviorError {s$1: "An undefined behavior was detected: undefined is not an instance of java.lang.String", e$1: $c_jl_ClassCastException, stackTrace$1: null, stackdata: TypeError: this.undef is not a function, constructor: function…}

I have been trying to trace the problem with no success so far. If anyone could point me in the right direction it would be highly appreciated ! Thanks in advanced
##### UPDATE

I was previously using angular 1.3.0, upgrading to 1.4.0 solved the problem. (It is important to note that it works just fine in 1.3.0 with vanilla JS)

**Comment by jokade** [comment]
Does this error also occur when you use `ng-show` instead of `ng-if`?

**Comment by ghost** [comment]
Correct, the error always occurs regardless of the template structure.
Also I was wrong, 1.4.0 did not fix it, It seems that it breaks how scoping works(at least data binding on the template does not work) but the directive runs without the exceptions.

##### Update

I have forked the sample application and added the code above so that it can be replicated:

https://github.com/AlexLourenco/scalajs-angulate-todomvc

**Comment by jokade** [comment]
Caused probably by the same reason explained in #62
