### ISSUE TITLE
Required field throws exception when empty

### ISSUE THREAD

**Issue by ghost** [jokade/scalajs-angulate#62]
Given the following:

``` html
<input ng-model = "ctrl.example" required>
```

If the model is changed to lets say "A" and then backspace is pressed, it will not delete the character and will throw an exception:

```
$c_sjsr_UndefinedBehaviorError {s$1: "An undefined behavior was detected: undefined is not an instance of java.lang.String", e$1: $c_jl_ClassCastException, stackTrace$1: null, stackdata: TypeError: this.undef is not a function, constructor: function…}
```

**Comment by jokade** [comment]
How is `example` defined in your controller?

**Comment by ghost** [comment]
Like so:

``` scala
import biz.enef.angulate.{ Scope, Controller }

import scala.scalajs.js
import scala.scalajs.js.UndefOr
import js.Dynamic.literal

import js.Dynamic.{ global => g }

class GeneralCtrl($scope: Scope) extends Controller {
    val $dynamicScope = $scope.asInstanceOf[js.Dynamic]

    var example         = ""
}
```

**Comment by jokade** [comment]
The property `example` probably needs to be defined as `UndefOr[String]` (see [this tip](https://github.com/jokade/scalajs-angulate/wiki/Tips---Tricks#use-jsundefort-for-vars-bound-to-input-fields)):

``` scala
/* ... */
var example: js.UndefOr[String] = ""
```

**Comment by ghost** [comment]
Thanks jokade, that did the trick! Feel free to close both this ticket and the one from the validation (the issue was caused by this for same for both).

If I may, it might be worth to link to the wiki (or reference some of the quirks ) in the README file as this went totally unnoticed by me.

Once again thank you and apologies for the hassle :)

**Comment by jokade** [comment]
No problem, it's not obvious and as you said: I really need to add a link from the Readme to the wiki page :)
-- Johannes
