### ISSUE TITLE
multiple ng-apps

### ISSUE THREAD

**Issue by RBleyenberg** [jokade/scalajs-angulate#63]
First of all thx for making this great library,

For me question, i'm looking at making an app with play and angulate lib and it's running smoothly.But the app requires multiple ng-apps running, after some searching if found this anwser http://stackoverflow.com/questions/18571301/angularjs-multiple-ng-app-within-a-page

But i'm abit lost on how to implement this with angulate where the createModule doesn't work multiple times...

Hopefully you can shine a light on this question.

**Comment by jokade** [comment]
> But i'm abit lost on how to implement this with angulate where the createModule doesn't work multiple times...

What happens when you call `angular.createModule()` more than once? Could you give a code example?

**Comment by RBleyenberg** [comment]
Yup i can do that,

first i did little test in plain js like so,

var myApp = angular.module('myApp',[]);
function MyCtrl($scope) {
    $scope.name = 'Superhero';
}
var myApp2 = angular.module('myApp2',[]);
function MyCtrl2($scope) {
    $scope.title = 'Superhero';
}

div ng-app="myApp" ng-controller="MyCtrl">
 Hello, {{name}}!
/div>
div ng-app="myApp2" ng-controller="MyCtrl2">
Hello, {{title}}!
/div>

above works

Then i tranfered it to angulate like so

object TodoApp extends JSApp {
  override def main(): Unit = {

```
val module = angular.createModule("todomvc", Nil)

module.controllerOf[TodoCtrl]("TodoCtrl")

val module2 = angular.createModule("todomvc2", Nil)

module2.controllerOf[TodoCtrl2]("TodoCtrl2")

dom.document.getElementById("scalajsShoutOut").textContent = SharedMessages.itWorks
```

  }
}

and what happens is that on inspection of the js file in console, the todomvc2 and todoctrl2 never get "made" also no error of any sort and var module does get loaded with totdoctrl.

Hope it helps,

**Comment by jokade** [comment]
Just to make sure: did you try a `sbt clean`?

**Comment by RBleyenberg** [comment]
did the sbt clean, didn't work. But after that, i also deleted all target maps (hard clean i guess :P) and it works both module in console.

thx for the fast answers, and help. Now for the real stuff and angulate.

Best Regards,

**Comment by jokade** [comment]
That's strange, `sbt clean`should suffice...
FYI: there is an issue (#52) with controllers defined in another file than the corresponding `module.controllerOf[]` call

**Comment by RBleyenberg** [comment]
Well prehaps it as to do with the fact that i'm running a multi domain sbt file (3 domain and scalajs). i'm likely to encounter it more so will investigated deeper, and report on any answers.

**Comment by jokade** [comment]
Do you mean a "multi-project" build? I'm using that as well with scala.js and it usually works quite well. Good luck!

**Comment by RBleyenberg** [comment]
yes multi-project, and i guess the word "usually" is in place here :P
