### ISSUE TITLE
ui-router

### ISSUE THREAD

**Issue by RBleyenberg** [jokade/scalajs-angulate#64]
Howdy Jokade,

Question, for the project i'm building i would like to add ui-router. After some searching i did see you personal have some issues posted at https://github.com/ludovicc/scalajs-angulate-uirouter.

So can i use that library safely with angulate ? or is there a other implementation...

Best Regards,

**Comment by jokade** [comment]
The library is great, it's just not published (that's one of my issues). My other issue is about a minor bug (which I solved in my own fork https://github.com/jokade/scalajs-angulate-uirouter).

FYI: "body scope" `Controllers` don't work with `ui-router` in scalajs-angulate 0.2.0. Either use `ScopeController`s, or the upcoming 0.2.1 (0.2.1-SNAPSHOT available from sonatype snapshots)

Cheers, Johannes

**Comment by RBleyenberg** [comment]
Okido, and even $animate pretty awesome within 2.1, great work and a deep bow :P
