### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by renataogarcia** [jokade/scalajs-angulate#82]
Hi,

Just wondering about the status of this really cool project? 

Cheers

**Comment by jokade** [comment]
Hi,

I was quite occupied with other projects over last few months... I'm planning a minor maintenance release (upgrade to scalajs-0.6.5), but other than that, I will probably put my spare time into the angulate2 lib. However, I'm using this library in 2 of my projects, so I won't abandon it any time soon. If you have feature request, please feel free to open an issue or a merge request :)

**Comment by renataogarcia** [comment]
> I will probably put my spare time into the angulate2 lib.

Makes sense. I'm also interested in the angulate2 version.

> However, I'm using this library in 2 of my projects, so I won't abandon it any time soon. If you have feature request, please feel free to open an issue or a merge request :)

Cool, will do! 
Thanks
