### ISSUE TITLE
Filter example

### ISSUE THREAD

**Issue by schmitch** [jokade/scalajs-angulate#84]
Hello, could you make a example on how to create a filter?
I tried it several times, however I couldn't get a reasonable output.

**Comment by jokade** [comment]
Ahh yes, the API for filters is unfortunately somewhat cumbersome ...
Here's the [example from the Angular.js guide](https://docs.angularjs.org/api/ng/provider/$filterProvider#register) with scalajs-angulate:

``` scala
class GreetService {
  def greet(name: String): String = s"Hello $name"
}

module.serviceOf[GreetService]

module.filter("greet",(greetService: GreetService) => {
  ((name:String) => {
    greetService.greet(name)
  }):js.Function
})
```

**Important**: If you want to inject a dependncy into the filter provider (here: `GreetService`) you must adhere to the [DI rules as explained for `module.config()`](https://github.com/jokade/scalajs-angulate#dependency-injection). You may drop some of the braces from the example, but you'll probably need the explicit `js.Function` type annotation, or Angular.js will complain about `v3 is not a function` (or something similar).

**Comment by schmitch** [comment]
@jokade oh thanks, I somehow missed the :js.Function

I actually also tried to use the controllerAs pattern, however I don't know how to access the compile time generated controller. and the httpservice .future didn't worked, too. Maybe I miss something. Does that stuff maybe depend on the Macro Compiler plugin?

**Comment by jokade** [comment]
>  I don't know how to access the compile time generated controller.

Could you give me a code snippet? I'm not sure if I understand what you intend to do.

**Comment by schmitch** [comment]
First:

``` scala
class UserService($http: HttpService) extends Service {
  def getAll() : Future[js.Array[User]] = $http.get("/users").future
}
```

Gives:

``` scala
type mismatch;
 found   : biz.enef.angulate.core.HttpPromise.RichHttpPromise[String]
 required: biz.enef.angulate.core.HttpPromise[?]
```

Second:

``` scala
@JSExport
object CounterModule {
@JSExport
val module = angular.createModule("counter")
module.controllerOf[CounterCtrl]
}

class CounterCtrl extends Controller {
  var count = 0

  def inc() = count += 1

  def dec() = count -= 1

  // private properties and functions are not exported to the controller scope
  private def foo() : Unit = ...
}
```

And then access that in normal js code. I have a old routerProvider where I want a view with this controller. (adding the module view `my.package.CtrlModule().name` works fine, actually not sure under which package the ctrl will be generated)
so 

```
when('/url', {
templateUrl: '',
controller: my.package.name.Ctrl,
controllerAs: 'vm',
})
```

**Comment by jokade** [comment]
1) have you tried a complete re-build? There is a [problem if a controller is specified separatley from the corresponding `module.controllerOf[]`](https://github.com/jokade/scalajs-angulate/wiki/Known-Problems#controller)

2) the future should work; I'm not sure what you mean with "Macro Compiler Plugin" (scalajs-angulate uses macros, but not a compiler plugin). Do you see the HTTP request/response in the console? If so, does the `onComplete` work as expected?

3) Router: hmm, I'm usually using ui-router, but I think that your example should work (although there's a typo in your code snippet - you probably meant `CountCtrl`). Also, you could try to specify the controller name explicitly with `module.controllerOf[CounterCtrl]("MyCtrl")`

**Comment by schmitch** [comment]
So this:

``` scala
package old.envisia.loki.templates

import biz.enef.angulate._
import biz.enef.angulate.core.HttpService

import scala.scalajs.js.annotation.JSExport

@JSExport
object App {

  class LokiTemplatesCtrl($http: HttpService) extends Controller {

    val demo = "Hase"

  }

  @JSExport
  val module = angular.createModule("ev.lokiConfigTemplates", Seq())
  module.controllerOf[LokiTemplatesCtrl]

}
```

Won't suffer from the bug? And would it export my controller to `old.envisia.loki.templates.App().LokiTemplatesCtrl`?

Edit: I'm still not sure how I could access my controller inside javascript..

And about the `.future` I can't even compile it.

This is the file with the service (no module yet):

``` scala
package old.envisia.loki.templates

import biz.enef.angulate._
import biz.enef.angulate.core.HttpService

import scala.scalajs.js


object TestModule {

  val module = angular.createModule("bla")
  //module.serviceOf[TestService]
  module.filter("bla", () => {
    ((x: String) => {

    }):js.Function
  })

}


class TestService($http: HttpService) extends Service{

  def bla() = $http.get[String]("/xyz").future

}
```

Error:

```
Compilation error
type mismatch;
 found   : biz.enef.angulate.core.HttpPromise.RichHttpPromise[String]
 required: biz.enef.angulate.core.HttpPromise[?]

```

**Comment by jokade** [comment]
That should work, although it is discouraged to define classes in package objects (scalac will emit a warning). I'm using this pattern for my controllers:

``` scala
class FooCtrl($http: HttpService) extends Controller {
  /* ... */
}
object FooCtrl {
  def apply(module: Module.RichModule) = module.controllerOf[FooCtrl]
}

object App {
  val module = angular.createModule(/* ... */)
  FooCtrl(module)
}
```

**Comment by schmitch** [comment]
And how do you access that in javascript?

**Comment by jokade** [comment]
Just add an `@JSExport` to the `App` object and then call `App()` from JavaScript. This will create the module and register the `FooCtrl`.

**Comment by schmitch** [comment]
so you call the controller with 'FooCtrl'? I get an `Argument 'FooCtrl' is not a function, got undefined`with that

**Comment by jokade** [comment]
> And about the .future I can't even compile it.

Hmm, seems like you found a regression :( that's a bug in the current macro implementation. I will try to fix it soon.

**Comment by jokade** [comment]
> so you call the controller with 'FooCtrl'? I get an Argument 'FooCtrl' is not a function, got undefinedwith that

How did you try to instantiate `FooCtrl`? It extends `Controller`, so it must be used with `as`.

**Comment by schmitch** [comment]
It's something like:

``` js
{
            template: old.envisia.loki.templates.LokiTemplate().template(),
            controller: 'BlablaCtrl as vm'
        }
```

However it looks like it can't find the BlablaCtrl

**Comment by jokade** [comment]
Is `BlablaCtrl` defined without package, or do you set the controller name explicitly with `controllerOf`?

**Comment by schmitch** [comment]
Oh my god. @jokade thanks.. I was so blind that I never called it via:  `'old.envisia.loki.templates.BlablaCtrl as vm'`

Edit: so with the `object BlablaCtrl { def apply(module...) }` I work around the bug, correct?

**Comment by schmitch** [comment]
@jokade btw. when wrap a httppromise with new HttpPromiseWrapper[String](promise) i get a future, however I'm not sure but I think futures on scalajs are horrible slow when it comes to change detection.

If I pull a HttpPromise[String] and apply it to a template variable the template updates it instantly, if I however have a future and run onComplete (the same as before) It takes a while until my template updates (however a println, will output the future directly)

Edit looks like it's caused by the ExecutionContext, they call setTimeout inside Implicits.queue ..

**Comment by jokade** [comment]
Well, a future is not really meant to be used in a Angular template (it's only intended to serve as a bridge between an Angular http request and some other _Scala_ code that relies on futures). The "common" design pattern for http requests in scalajs-angulate looks like:

``` scala
class FooCtrl(barService: BarService) extends Controller {
  var foo: String = ""
  barService.getFoo().onSuccess( foo = _ )
}

class BarService($http: HttpService) extends Service {
  def getFoo() = $http.get[String]("/foo")
}
```

> I think futures on scalajs are horrible slow when it comes to change detection

Yes, Angular.js change detection works by deep-polling all properties on the object. In the case of a Scala class this means checking all class properties, including the entire "class hierarchy". Hence, never use change detection a Scala class instance...

**Comment by schmitch** [comment]
As said it's not the future, I need future to group multiple HttpPromises, it's the executioncontext which makes these problems. I never use scalajs objects I always use js.Dictonary for templates.

**Comment by jokade** [comment]
> I never use scalajs objects I always use js.Dictonary for templates.

Then I don't understand why there should be a connection between the future and change detection :?

**Comment by schmitch** [comment]
because a future needs a executioncontext and the old runNow was:

``` scala
private[concurrent] object RunNowExecutionContext
    extends ExecutionContextExecutor {

  def execute(runnable: Runnable): Unit = {
    try {
      runnable.run()
    } catch {
      case t: Throwable => reportFailure(t)
    }
  }

  def reportFailure(t: Throwable): Unit =
    t.printStackTrace()

}
```

That is deprecated.

The new one is:

``` scala
private[concurrent] object QueueExecutionContext
    extends ExecutionContextExecutor {

  def execute(runnable: Runnable): Unit = {
    js.timers.setTimeout(0) {
      try {
        runnable.run()
      } catch {
        case t: Throwable => reportFailure(t)
      }
    }
  }

  def reportFailure(t: Throwable): Unit =
    t.printStackTrace()

}
```

And angularjs won't know anything about things inside a setTimeout. (http://www.sitepoint.com/understanding-angulars-apply-digest/) having a $scope: Scope inside the Controller and calling $scope.$apply() will actually update the view even when I use the queue execution context.

**Comment by jokade** [comment]
Ok, I thought you were talking about detecting changes on an object during a digest cycle; but your problem is that a future resolved after a digest cycle triggered by a http request does not trigger a new disgest cycle? Well, you don't need a Scala future to combine promises; just use `$q.all()` for that.

**Comment by schmitch** [comment]
@jokade I know about $q.all however it's not as good as using future's. 
Currently ScalaJS's Future needing a ExecutionContext, as Scala, however since ScalaJS 0.6.6 there is a new ExecutionContext which will wrap all future's inside a `setTimeout` call and when you use setTimeout in AngularJS you will actually hide anything inside that from the digest cycle so you need to manually trigger it.

**Comment by jokade** [comment]
I didn't upgrade to 0.6.6 yet, so I haven't noticed that `runNow` has been deprecated (however, `queue` has always been there). I'm not sure what made the Scala.js team do that (seems to me like a case of "it's just not the correct way"); but if the runNow works fine for you, why don't you just include a copy in your own code? Or maybe you could make a copy of the `queue` context, which automatically triggers a digest cycle?

Anyway, the problem you describe is inherent to angular.js and not really related to Scala.js or this library (as pointed out by the article you've referenced above) :(

**Comment by jokade** [comment]
> Or maybe you could make a copy of the queue context, which automatically triggers a digest cycle?

i.e. using `$timeout` instead of `setTimeout`

**Comment by schmitch** [comment]
However yeah I implemented the old ExecutionContext. Still totally aweful

**Comment by schmitch** [comment]
Oh and I will close that and make a PR for the documentation part of filters.
